name: Go
on:
  issue_comment:
    types:
      - created
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Custom Action
      uses: yusuf-erdem/yusufs-test-wiser@v1
      with:
        timeout: 245 ms
