name: Go staging
on:
  issue_comment:
    types:
      - created
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:
env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.us
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  PR_NUMBER: ${{ github.event.number }}
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.us
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      if: always()
      uses: runforesight/foresight-workflow-kit-action@v1
      with:
        api_key: 833262ba-ed1f-4b63-8ca8-901664cc501b
    - uses: actions/checkout@v3


    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Test Go
      run: |
          go test -v -run Test_Sum -json ./... > ./test-report1.json -coverprofile=coverage1.out
    - name: Foresight Action
      if: success() || failure()
      uses: runforesight/foresight-test-kit-action@v1
      with:
        api_key: 833262ba-ed1f-4b63-8ca8-901664cc501b
        test_framework: golang
        test_format: json
        test_path: ./test-report.json
        coverage_format: golang
        coverage_path: |
            coverage1.out
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
