name: Go Test Success
on:
  issue_comment:
    types:
      - created
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:
env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.service.runforesight.me
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  PR_NUMBER: ${{ github.event.number }}
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.me

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      if: always()
      uses: runforesight/foresight-workflow-kit-action@v1
      with:
        api_key: ${{ secrets.F_LAB_API_KEY }}
    - uses: actions/checkout@v3


    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Test Go
      run: |
        go test -v  | tee ./test-report-custom.txt -coverprofile=coverage2.out -run ExampleGet
    - name: Foresight Action
      if: success() || failure()
      uses: runforesight/foresight-test-kit-action@v1
      with:
        api_key: ${{ secrets.F_LAB_API_KEY }}
        test_framework: golang
        test_format: text
        test_path: ./test-report-custom.txt
        coverage_format: golang
        coverage_path: |
            coverage2.out
